DROP TABLE security."MEMBER_ROLE_PERMISSION";
DROP TABLE security."MEMBER_ROLE";
DROP TABLE security."APPLICATION";
DROP TABLE security."ROLE";
DROP TABLE security."PERMISSION";
DROP TABLE security."MEMBER";
DROP TABLE security."FLYWAY_SCHEMA_HISTORY";