CREATE TABLE APPLICATION (
    ID VARCHAR ( 255 ) PRIMARY KEY
);

CREATE TABLE ROLE (
    ID VARCHAR ( 255 ) PRIMARY KEY
);

CREATE TABLE PERMISSION (
    ID VARCHAR ( 255 ) PRIMARY KEY
);

CREATE TABLE MEMBER (
    ID IDENTITY PRIMARY KEY,
    USERNAME VARCHAR ( 255 ) UNIQUE NOT NULL,
    PASSWORD VARCHAR ( 255 ) NOT NULL,
    EMAIL VARCHAR ( 255 ) UNIQUE NOT NULL,
    CREATED_ON TIMESTAMP NOT NULL
);

CREATE TABLE MEMBER_ROLE (
    ID IDENTITY PRIMARY KEY,
    MEMBER_ID INTEGER NOT NULL,
    APPLICATION VARCHAR ( 255 ) NOT NULL,
    ROLE VARCHAR ( 255 ) NOT NULL,
    CONSTRAINT FK_MEMBER_ROLES_USER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(ID),
    CONSTRAINT FK_MEMBER_ROLES_ROLE FOREIGN KEY (ROLE) REFERENCES ROLE(ID),
    CONSTRAINT FK_MEMBER_ROLES_APPLICATION FOREIGN KEY (APPLICATION) REFERENCES APPLICATION(ID)
);

CREATE TABLE MEMBER_ROLE_PERMISSION (
    ID IDENTITY PRIMARY KEY,
    MEMBER_ROLE_ID INTEGER NOT NULL,
    PERMISSION VARCHAR ( 255 ) NOT NULL,
    CONSTRAINT FK_MEMBER_ROLE_PERMISSION_MEMBER_ROLE FOREIGN KEY (MEMBER_ROLE_ID) REFERENCES MEMBER_ROLE(ID),
    CONSTRAINT FK_MEMBER_ROLE_PERMISSION_PERMISSION FOREIGN KEY (PERMISSION) REFERENCES PERMISSION(ID)
);